### ISSUE TITLE
Just Citing/Acknowledging Your Work

### ISSUE THREAD

**Issue by anonhostpi** [noah-severyn/csDBPF#17]
Gonna open then immediately close this issue. Just reaching out to let you know that my DBPF wiki cites this repository.
- wiki: https://anonhostpi.github.io/DBPF.js/docs/other/spec/

I'm avidly working on my own DBPF reader. If you see anything missing from my wiki (...or my lib), feel free let me know! I'm avidly working on them every day

I just wanted to be sure you knew I was citing your work! Its nice to see projects keeping SimCity alive! You may want to take a look at the develop branch of the Sims4Tools project. Out of all of the DBPF parsers I've researched, there's seems to be the most comprehensive and in depth. Of course, there's is tailored towards  newer revisions of DBPF v2.0 (or 2.1?), but I'm sure it would prove helpful to you.

I have a fork of the develop branch: https://github.com/anonhostpi/Sims4Tools

I'm also working on translating entries to Kaitai, so that it is easier to understand them. Here's my Kaitai for GEOM entries (I believe these used to be called OBJD in DBPF v1.0): https://github.com/anonhostpi/DBPF.js/blob/main/docs/spec/sections/ResourceTypes.md#structure
- expand the .ksy files there.

**Comment by noah-severyn** [comment]
@anonhostpi Thank you I appreciate it! :)

If you haven't already seen, I also put together a list of repositories [here](https://github.com/noah-severyn/csDBPF/wiki/Other-DBPF-Resources) which you can also steal from, though it's more focused on the DBPF 1.0 implementations as that's what I'm interested in for SimCity 4.

**Comment by anonhostpi** [comment]
Ok, took me a bit, because I've been working on getting multithreaded support started in my tool, but I've now added all of those to the source documents for my wiki: https://github.com/anonhostpi/DBPF.js/blob/main/docs/spec/README.md.

The wiki (https://anonhostpi.github.com/DBPF.js) will be refreshed on the next release.

**Comment by anonhostpi** [comment]
Sorry about that spammy bit. Went into each of the repos I didn't have links to yet, and sent them similar messages. Those issues just link back to this one.
